base:
  branch: main
  dbt:
    commands:
    - dbt deps
    - dbt build --target jaffle_shop
  piperider:
    command: piperider run --data-source jaffle_shop
target:
  dbt:
    commands:
    - dbt deps
    - dbt build --target jaffle_shop
  piperider:
    command: piperider run --data-source jaffle_shop
